### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by marwie** [anncwb/vite-plugin-compression#10]
Hello,
I've cloned this repo and ran ``npm install`` in the example directory. When running ``npm run build`` it fails with the following error

```
λ npm run build

> ts-example@0.0.0 build C:\git\vite-plugin-compression\example
> vite build

 > vite.config.ts:3:28: error: Could not resolve "../dist/index"
    3 │ import viteCompression from '../dist/index';
      ╵                             ~~~~~~~~~~~~~~~

failed to load config from C:\git\vite-plugin-compression\example\vite.config.ts
error during build:
Error: Build failed with 1 error:
vite.config.ts:3:28: error: Could not resolve "../dist/index"
    at failureErrorWithLog (C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:1493:15)
    at C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:1151:28
    at runOnEndCallbacks (C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:941:63)
    at buildResponseToResult (C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:1149:7)
    at C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:1258:14
    at C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\git\vite-plugin-compression\example\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ts-example@0.0.0 build: `vite build `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ts-example@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by marwie** [comment]
Ah sorry ok I didnt realize I would have to install and build the parent directory also
